### ISSUE TITLE
Add support for 10, 11, 12

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-addons-repo-template#103]
This is necessary if we want to be able to unplug travis.

TODO

- [ ] extract the flake8 config from MQT
- [ ] extract the pylint config from MQT
- [ ] create a pre-commit config that uses flake8 and pylint with the above configs
- [ ] create a GitHub workflow for tests (the template we have right now should be ok and work for 10, 11, 12 too)

**Comment by sbidoul** [comment]
I think this task is the last one before we can stop Travis and switch all repos to GitHub actions.

If anyone wants to help with it, this is most welcome. I'm happy to provide any guidance that would be necessary.

**Comment by sbidoul** [comment]
@carmenbianca that's great! I have started something in #117. Feel free to pick it up from there. I will not have much time to work on this myself before mid-end march, but let me know if you have any question or doubt on how to move forward.

**Comment by carmenbianca** [comment]
@sbidoul I did a review and some suggestions. I'm a little lost on what specifically is missing/todo. https://github.com/OCA/l10n-italy/pull/2658 demonstrates that #117 mostly works. The test failures seem to be true positives for the maintainers to address.

**Comment by sbidoul** [comment]
> mostly works

"mostly" is the keyword :)

This needs to be made to work and tested in a few representative repos.
