### ISSUE TITLE
Runboat badge instead of runbot one

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-addons-repo-template#105]
Similar to #104, but with runboat.

**Comment by joao-p-marques** [comment]
I am not sure which link we could put with the new Runboat UI. @sbidoul looking at the code, I tried `https://runboat.odoo-community.org/webui/builds.html?repo={{ repo_slug }}` but it didn't work. Is this supported in the current implementation?

**Comment by sbidoul** [comment]
Something like this works: https://runboat.odoo-community.org/builds?repo=oca/mis-builder&target_branch=14.0

**Comment by sbidoul** [comment]
Another thing I would like to do is setup a nginx redirect on runbot.odoo-community.org to runboat, so links in the wild (in README.rst for instance) will continue to make sense. We'll do that when we shutdown runbot.
