### ISSUE TITLE
Remove .t2d.yml

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-addons-repo-template#108]
This .t2d.yml idea did not fly.

Now that we have runboat and we are probably going to shutdown runbot, this must be removed from the template, and we need a task to removed it where it was created.

**Comment by pedrobaeza** [comment]
Well, having there is harmless AFAIK, although it's good to remove it from the template for future scaffoldings.

**Comment by sbidoul** [comment]
It's harmless indeed. But let's keep the room clean :)
