### ISSUE TITLE
travis_apt_packages produces bad .travis.yml entry

### ISSUE THREAD

**Issue by simahawk** [OCA/oca-addons-repo-template#109]
See this PR https://github.com/OCA/server-auth/pull/331
No matter how I pass `travis_apt_packages` to the answer, it always generate a quoted string.
I guess it has to deal w/ [`{{ package|tojson }}`](https://github.com/OCA/oca-addons-repo-template/blob/f1fb8730d3a6acd650e95362ef83ca5c65ad9173/src/%7B%25%20if%20ci%20%3D%3D%20'Travis'%20%25%7D.travis.yml%7B%25%20else%20%25%7D.t2d.yml%7B%25%20endif%20%25%7D.jinja#L28) so I wonder: do we really need to call `tojson`?

**Comment by joao-p-marques** [comment]
Is there any problem in having it with quotes? I guess it could be needed for some packages that have spaces in the middle of the name...

**Comment by sbidoul** [comment]
I'd recommend converting the repo to GitHub actions.
