### ISSUE TITLE
[RFC][15.0] make pylint W8120(translation-positional-used) optional

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-addons-repo-template#110]
While migrating modules to 15.0 we noticed this new check is now enabled by default.

While interesting in principle (not always, though) this is creating a lot of churn, including the need to re-do a lot of translations.

I suggest to move this check to pylint-optional.

Thoughts?

**Comment by pedrobaeza** [comment]
Well, if we don't force it, we don't get rid off the underlying problem: translations can be incorrect due to the positional arguments. It's not a usual problem in our romance languages, but it is for others. Should we be solidary with that?

**Comment by sbidoul** [comment]
Good point, thanks!.
