### ISSUE TITLE
Support for the new "Native Javascript Modules" ( `/** @odoo-module **/` ) without filename globs

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/oca-addons-repo-template#123]
Support for the new js files has been added here:
- https://github.com/OCA/oca-addons-repo-template/pull/86

At least to me, having to name a file `.esm.js` is not intuitive and finding this information took me a while
Ideally we'd want eslint to be smart enough to choose the right sourceType when parsing a file, and so we could drop this glob matching.

Here's a stackoverflow answer that claims it's possible: 
- https://stackoverflow.com/a/69310095

It requires creating a custom eslint plugin to identify ("disambiguate") the files.
In our case, all this plugin would need to do is try to find  `/** @odoo-module **/` in the file header

**Comment by Yajo** [comment]
> finding this information took me a while

FTR It's in the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0
