### ISSUE TITLE
flake precommit consider import not used in __init__ files

### ISSUE THREAD

**Issue by flotho** [OCA/oca-addons-repo-template#126]
Hi,

First of all, sorry if it's not the proper repo to open this issue 
I'm facing an issue while using flake in precommit:
![image](https://user-images.githubusercontent.com/1043935/156741950-55f894eb-d268-4b5a-9446-ad23eac03cc7.png)

all the import in __init_ files are considered as not used.
Obviously it looks to be already known : https://stackoverflow.com/questions/8427701/how-to-ignore-pyflakes-errors-imported-but-unused-in-the-init-py-file

I'm wondering if it could come from my environment, or if there is some options to setup or whatever...

Any feedback would be appreciated.

Regards

**Comment by flotho** [comment]
obviously # noqa seems to be the answer

**Comment by Yajo** [comment]
> I'm wondering if it could come from my environment

Probably yes. Our template fixes that problem out of the box: https://github.com/OCA/oca-addons-repo-template/blob/22f6839214ea79f536cb167bdb4c647b42c41496/src/.flake8#L11-L12
