### ISSUE TITLE
Error on updating 13.0 branches

### ISSUE THREAD

**Issue by etobella** [OCA/oca-addons-repo-template#135]
When I updated copier on 13.0 branch from social, an error was raised for pre-commit. The solution I found was not removing this:

https://github.com/OCA/social/pull/878/files#diff-ac5eead3f3ce4863c524fff031a87b7aecccb4a0493df087a4e1c704a1505036L14-L19

Is it needed on the script?

**Comment by sbidoul** [comment]
@etobella the link you provide is unclear.

**Comment by etobella** [comment]
@sbidoul Yes, github is hiding the selected lines:

https://github.com/OCA/social/blob/13.0/.github/workflows/pre-commit.yml#L19-L24

I hope this is clear now :smile:

**Comment by pedrobaeza** [comment]
Is this solved?
