### ISSUE TITLE
Error: Docker login for 'ghcr.io' failed with exit code 1

### ISSUE THREAD

**Issue by legalsylvain** [OCA/oca-addons-repo-template#138]
Hi, 

I have a recent error on my CI that is using OCA rules.

Since today, I have trouble to execute ``github`` CI. (github workflows, oca-bot, etc...)

docker hub seems to ask a login. 

Did you faced similar issue ?

```
Starting job container
  /usr/bin/docker --config /home/runner/work/_temp/.docker_f5e17f3e-07be-4a21-82d1-c29f8289b6fd login ghcr.io -u github-grap-bot --password-stdin
  Error: Docker login for 'ghcr.io' failed with exit code 1
```

Ref : https://github.com/grap/odoo-addons-intercompany-trade/runs/6155927785?check_suite_focus=true#step:2:15

Note : sorry if it's not the correct place for the bug report.

regards.

**Comment by yajo** [comment]
That's github problem: https://www.githubstatus.com/incidents/b40k7ckrs7sp

**Comment by legalsylvain** [comment]
> That's github problem: https://www.githubstatus.com/incidents/b40k7ckrs7sp

Thanks @yajo !
