### ISSUE TITLE
Label for repo?

### ISSUE THREAD

**Issue by Yajo** [OCA/oca-addons-repo-template#14]
I don't have permissions, but it would be nice if you label the repo as [copier-template](https://github.com/topics/copier-template) topic.

**Comment by sbidoul** [comment]
Done. BTW, I had already tagged v1.0.0

**Comment by Yajo** [comment]
Thanks!

I think it would be better if you publish releases through the GitHub UI instead of just simple tags, so we can include a brief description of what's new in that version. It can serve as a changelog, but easier to maintain that a `CHANGELOG` file. Just a suggestion. :wink:
