### ISSUE TITLE
Codecov not configured correctly

### ISSUE THREAD

**Issue by yajo** [OCA/oca-addons-repo-template#142]
## Describe the bug
I'm not sure if this is the place to raise this issue, but there's some problem with how codecov interprets information, or something related with it.

Check out the warning introduced [here](https://github.com/OCA/account-financial-tools/pull/1424/checks?check_run_id=6775598574) for https://github.com/OCA/account-financial-tools/pull/1424.

Just in case it gets garbage-collected, I put here a screenshot:

![imagen](https://user-images.githubusercontent.com/973709/172794679-16fa6cbe-c48d-4683-9bbf-0cbfaa86e73a.png)

The warning is wrong because [that line was of course executed by a test](https://github.com/OCA/account-financial-tools/runs/6775473254?check_suite_focus=true#step:8:344) (it *is* a test!):

![imagen](https://user-images.githubusercontent.com/973709/172795134-aa2326aa-3cdf-49ea-bffc-82f0a4855de3.png)

**Expected behavior**
No warning.

**Comment by sbidoul** [comment]
Could it be that line 61 raised and line 62 was not executed?

**Comment by legalsylvain** [comment]
If 61 is not executed, test fails. Dont you think ?

**Comment by sbidoul** [comment]
The test will succeed if 61 raises the expected ValidationError.

**Comment by yajo** [comment]
Ah of course! I didn't realize this is an assertRaises. 🤦🏼‍♂️ 

Thanks folks.
