### ISSUE TITLE
Add PSC Team on README

### ISSUE THREAD

**Issue by Shide** [OCA/oca-addons-repo-template#147]
**Is your feature request related to a problem?**
A couple of days ago, someone was pinging to OCA/oca-contributors on a simple PR sending a lot of emails and making a lot of noise.

**Describe the solution you'd like**
A link to the [PSC Team](https://odoo-community.org/psc-teams) who are maintaining the repo on the README could help in order to know what are the maintainers and ask for help in such case.

**Describe alternatives you've considered**
- Adding a section on the right bar on Github if it's possible, but on the about section, only one link is allowed.
- Set visibility of OCA/oca-contributors group as secret (only owners can ping and view this group). And maybe other groups that can be suspected to send thousands of emails like this one.

**Additional context**
Comments from:
https://github.com/OCA/timesheet/pull/440#issuecomment-1178621323
https://github.com/OCA/timesheet/pull/473#issuecomment-1178626410

**Comment by Shide** [comment]
Related to https://github.com/OCA/oca-addons-repo-template/issues/140

**Comment by yajo** [comment]
Oops, isn't this a duplicate?
