### ISSUE TITLE
prettier-xml==0.12.0 broken on Fedora 36

### ISSUE THREAD

**Issue by carmenbianca** [OCA/oca-addons-repo-template#155]
## Module

N/A

## Describe the bug

When running pre-commit using prettier-xml==0.12.0 on Fedora (Silverblue) 36, prettier deletes the contents of XML files instead of formatting them. I do not know why this is.

## To Reproduce
**Affected versions**: <15

1. Create a Fedora Docker image / virtual machine
2. Install pre-commit
3. Run pre-commit on an OCA repo.

**Expected behavior**

The XML is formatted.

**Additional context**

- OS: Fedora Silverblue 36
- NPM version: 8.3.1
- Node version: 16.14.0
- pre-commit version: 2.17.0

**Comment by yajo** [comment]
I use Silverblue 36 too and it works for me. 🤔 

Have you tried posting an issue upstream?

**Comment by carmenbianca** [comment]
@yajo I found the issue; thanks for verifying it's not a Fedora/Silverblue problem.

I had a ~/node_modules directory that was a symbolic link to .local/lib/node_modules. I also had a package.json (and .lock) file in my home directory for reasons I don't remember. After removing both the symbolic link and the package.json files, I get normal behaviour again.

Strangely, I didn't get broken behaviour on newer releases of prettier-xml.

Closed NOTABUG :)
