### ISSUE TITLE
[RFC] Static analysis security checks

### ISSUE THREAD

**Issue by dreispt** [OCA/oca-addons-repo-template#168]
Today, many code quality check services include scans for known security issues.
For Python, there seems to be available a FLOSS tool for this: bandit (https://github.com/PyCQA/bandit).

We should consider including it in MQT.

**Comment by legalsylvain** [comment]
Hi. 

I justed tested bandit for OCA/server-tools/14.0 branch.

The result is : 
```
Code scanned:
	Total lines of code: 19541
	Total lines skipped (#nosec): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0.0
		Low: 22.0
		Medium: 37.0
		High: 2.0
	Total issues (by confidence):
		Undefined: 0.0
		Low: 5.0
		Medium: 6.0
		High: 50.0
```

Tested here : https://github.com/OCA/server-tools/pull/2460

The logs : https://github.com/OCA/server-tools/actions/runs/3432559590/jobs/5721962372#step:7:729

Well, at the first sight : 
- It generates a lot of issues on an existing and recent repo. (61!)
- Some points are interesting
- As a maintainers of some repo, I would find it tedious to have to correct problems on existing branches.

What do you think ?

**Comment by sbidoul** [comment]
> It generates a lot of issues on an existing and recent repo

14.0 is almost out of support, Sylvain :stuck_out_tongue: 

> As a maintainers of some repo, I would find it tedious to have to correct problems on existing branches.

This can't be added to existing branches. But this could be enabled behind a copier question for maintainers who want to test it.
