### ISSUE TITLE
UnicodeDecodeError with python 3.11

### ISSUE THREAD

**Issue by FrancescoBallerini** [OCA/oca-addons-repo-template#192]
I am trying to find proper configurations to make contributions here and there, and since I am not experience either with OCA infrastructure and git, I'm probably also missing some config steps. Despite that, I am reporting this as @sbidoul read my message on Discord channel, and told me that this is likely a bug (not the first log i report, but the second one).

## Describe the bug
I have run pre-commit and firstly got an issue about the permission to remove VERSION.txt file , this is probably a misconfiguration by me (not enough permission, as log say eheh), so as a quick-fix I have tried to manually remove VERSION.txt file and the following warning disappeared and pre-commit run almost smoothly:

```
forbidden files......................................(no files to check)Skipped
en.po files cannot exist.............................(no files to check)Skipped
Update pre-commit excluded addons........................................Passed
Fix the manifest website key.........................(no files to check)Skipped
autoflake............................................(no files to check)Skipped
black................................................(no files to check)Skipped
prettier (with plugin-xml)...........................(no files to check)Skipped
eslint...............................................(no files to check)Skipped
- hook id: eslint
Trim Trailing Whitespace.............................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Debug Statements (Python)............................(no files to check)Skipped
Fix python encoding pragma...........................(no files to check)Skipped
Check for case conflicts.............................(no files to check)Skipped
Check docstring is first.............................(no files to check)Skipped
Check that executables have shebangs.................(no files to check)Skipped
Check for merge conflicts............................(no files to check)Skipped
Check for broken symlinks............................(no files to check)Skipped
Check Xml............................................(no files to check)Skipped
Mixed line ending....................................(no files to check)Skipped
pyupgrade............................................(no files to check)Skipped
isort except __init__.py.............................(no files to check)Skipped
Generate default setup.py for an addons directory........................Failed
- hook id: setuptools-odoo-make-default
- exit code: 1

rm: cannot remove 'C:\Users\Utente\Documents\GitHub\product-attribute-14.0-add_pricelist_percent_change_supplierinfo\setup\_metapackage/VERSION.txt': Permission denied
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Scripts\setuptools-odoo-make-default.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\make_default_setup.py", line 413, in main
    clean_setup_addons_dir(args.addons_dir, args.odoo_version_override)
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\make_default_setup.py", line 323, in clean_setup_addons_dir
    subprocess.check_call(["rm", "-rf"] + paths_to_remove)
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rm', '-rf', 'C:\\Users\\Utente\\Documents\\GitHub\\product-attribute-14.0-add_pricelist_percent_change_supplierinfo\\setup\\_metapackage']' returned non-zero exit status 1.

Generate requirements.txt for an addons directory....(no files to check)Skipped
flake8...............................................(no files to check)Skipped
pylint with optional checks..........................(no files to check)Skipped
- hook id: pylint_odoo
Check for Odoo modules using pylint..................(no files to check)Skipped
```

I run pre-commit again and this time it wasn't skipping all tests, actually it went all good except for this one:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Scripts\setuptools-odoo-get-requirements.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\get_requirements.py", line 126, in main
    requirements = _get_requirements(
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\get_requirements.py", line 73, in _get_requirements
    metadata = get_addon_metadata(addon_dir, **overrides)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\core.py", line 462, in get_addon_metadata
    smeta = get_addon_setuptools_keywords(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\core.py", line 534, in get_addon_setuptools_keywords
    "long_description": _get_long_description(addon_dir, manifest),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\core.py", line 224, in _get_long_description
    return rf.read()
           ^^^^^^^^^
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2305: character maps to <undefined>

```

<strike>EDIT: I was trying to do some test commit to provide you a better log for this last one, but the error seems to be disappeared at the moment, I am not quite sure what happened, it seems it's magically fixed after pc restart.

I am not sure if I should post this issue, but considering theese days I am doing a some cleaning operations to re-organize my local repositories, I think I can post this and either close it in a few days or update it with new informations. </strike>

&rarr; figured out why I was not receiving error anymore, basically I was missing the module that was causing the issue. Watch the message below

**Additional context**
To give better context I develop on ubuntu 20.04, but to make "git" operations I work on windows10 machine where I have recently upgraded from python 3.7 to python 3.11. 

As I said I am not experienced with OCA infrastructure, git, PIP packages and all of these stuff, and I upgraded python because after a few month I was going to upgrade some PR I made, and post something new as well. I forgot everything I have learned about git few month ago and started from scratch again, was trying to configure a local repo but had issues with pre-commit. 

Some problems have been solved with python upgrade <strike>but now I got the issue that I have reported</strike>. I hope this is useful to fix something if it's a bug, but I am aware that it might just be small configuration issues with pip packages or else. 

Let me know if you want me to provide more information or do some tests.

Thanks in advance,
Francesco Ballerini

**Comment by FrancescoBallerini** [comment]
I figured out why the log about 'charcode map' was missing: 

as I stated before I was performing some "re-ordering operations" in my local repositories, and I missed a module in the repo for this PR https://github.com/OCA/product-attribute/pull/1315 , once I have added the module and executed pre-commit it raised the error, I have now a full log:

```
C:\Users\Utente\Documents\GitHub\product-attribute\14.0-add_pricelist_percent_change_supplierinfo>git commit -m "update add pricelist_percent_change_supplierinfo"
forbidden files......................................(no files to check)Skipped
en.po files cannot exist.............................(no files to check)Skipped
Update pre-commit excluded addons........................................Passed
Fix the manifest website key.............................................Passed
autoflake................................................................Passed
black....................................................................Passed
prettier (with plugin-xml)...........................(no files to check)Skipped
eslint...............................................(no files to check)Skipped
- hook id: eslint
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Debug Statements (Python)................................................Passed
Fix python encoding pragma...............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check that executables have shebangs.....................................Passed
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Xml............................................(no files to check)Skipped
Mixed line ending........................................................Passed
pyupgrade................................................................Passed
isort except __init__.py.................................................Passed
Generate default setup.py for an addons directory........................Passed
Generate requirements.txt for an addons directory........................Failed
- hook id: setuptools-odoo-get-requirements
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Scripts\setuptools-odoo-get-requirements.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\get_requirements.py", line 126, in main
    requirements = _get_requirements(
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\get_requirements.py", line 73, in _get_requirements
    metadata = get_addon_metadata(addon_dir, **overrides)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\core.py", line 462, in get_addon_metadata
    smeta = get_addon_setuptools_keywords(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\core.py", line 534, in get_addon_setuptools_keywords
    "long_description": _get_long_description(addon_dir, manifest),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utente\.cache\pre-commit\repo6o41sg2k\py_env-python3\Lib\site-packages\setuptools_odoo\core.py", line 224, in _get_long_description
    return rf.read()
           ^^^^^^^^^
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2368: character maps to <undefined>

flake8...................................................................Passed
pylint with optional checks..............................................Passed
- hook id: pylint_odoo
- duration: 1.9s
Check for Odoo modules using pylint......................................Passed
```

The charmap thing might be a bug as stated from @sbidoul even if, at this point I think I am doing something wrong in the configuration, because I have also noticed that in my PR's my setup tools folder seems to be missing and VERSION.txt file is outdated. I am not sure though, if issues are related.

**Comment by sbidoul** [comment]
Hello,

Thanks a lot for reporting!

> The charmap thing might be a bug 

It is a bug: https://github.com/acsone/setuptools-odoo/pull/109, probably revealed because your python installation does not use utf-8 by default. I'll update the repo template but it might take a while to be applied to all OCA repos.

> Le temps pass vite

The `setup/` directory is generated by pre-commit. I have personally never tested it myself on Windows.
It requires permissions to generate symbolic links which is not always enabled by default on Windows.
Although your error with VERSION.txt looks like a permission issue in a part that does not need symlinks. 
It might be something due to your environment, I'm not sure.

You might have more success by running in WSL.

**Comment by FrancescoBallerini** [comment]
Thank you for these precious informations (and for updating the repository) !

It seems that pre-commit in this case wasn't able/allowed to change single quote into double quote, on the module that was raising the UnicodeDecodeError. Since it was just a couple of lines I changed it manually, and pre-commit test passed without issues. 

Unfortunally it did not impact on VERSION.txt and setup folder, but no problem, I will keep experimenting and try to figure out what I need. I will start by enabling utf-8 encoding and will definitely try to give a look into WSL.

**Comment by FrancescoBallerini** [comment]
Hi @sbidoul , I am here again to ask for additional hints, if possible.

I finally decided to switch to a very simple ubuntu 20.04 environment to update my github works. I hoped that it would have automatically lead to conflict resolution for setuptools/ metapackage version, although my PR's still have conflicts and in the last days I have noticed that a message also appeared as shown in the image below:


![image](https://user-images.githubusercontent.com/103839892/236657207-daed99e2-84a9-4a60-b833-d6d3e1cef479.png)


I am not sure what is causing this trouble, I might just miss something that is generally considered obvious like some required packages, or I'm possibly making newbie mistakes. I have tried to guess by byself by searching for a technical documentation for the contributions, but I am not sure where to search.

I have searched mostly in [OCA guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst) but didn't find anything about that could help me to figure out. Not that I really expected to find something there since those are not technical guidelines, but if there is a proper place where I can look that you can reccomend (video or documentation) I will make a good use of it. 

At the moment what I did is to set a normal git local repository, install pre-commit and I ensure python 3.8 is used by running command 

`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8`

and then `--version`

Then I simply deleted the setup folder locally and made a commit, so it gets created again, but problem is not fixed. 

I know it is hard to guess with these few informations, but do you or someone else have an idea of what might be the issue?
