### ISSUE TITLE
Error: No such option: --if-source-changed

### ISSUE THREAD

**Issue by zamberjo** [OCA/oca-addons-repo-template#206]
## Describe the bug
After updating a repository (e.g. OCA/l10n-spain/tree/15.0) an error appears in the hook "oca-gen-addon-readme".

```bash
Usage: oca-gen-addon-readme [OPTIONS]
Try 'oca-gen-addon-readme --help' for help.

Error: No such option: --if-source-changed
```

It seems that revisions ["ab1d7f6" (<15)](https://github.com/OCA/oca-addons-repo-template/blob/master/src/.pre-commit-config.yaml.jinja#L12C8-L12C8) and ["dfba427ba03900b69e0a7f2c65890dc48921d36a" (<16)](https://github.com/OCA/oca-addons-repo-template/blob/master/src/.pre-commit-config.yaml.jinja#L29) do not have such an option. While ["969238e47c07d0c40573acff81d170f63245d738"](https://github.com/OCA/oca-addons-repo-template/blob/master/src/.pre-commit-config.yaml.jinja#L46) does.

## To Reproduce
Update the template in any repository in version 15.0 - 16.0

**Comment by yajo** [comment]
> Update the template in any repository in version 15.0 - 16.0

16.0 works fine: https://github.com/OCA/web/pull/2609

It's the rest of branches that fail.
