### ISSUE TITLE
`org_slug` is ignored

### ISSUE THREAD

**Issue by sergiocorato** [OCA/oca-addons-repo-template#209]
## Module
n.a.

## Describe the bug
OCA is used as `org_slug` even if a different one is set.

## To Reproduce
**Affected versions**:
tags >= 1.16.0

1. copy or update copier template
2. launch `pre-commit run -a`

**Expected behavior**
`org_slug` is used as defined in `.copier-answers.yml`

**Additional info**
python version 3.8.16
pydantic==1.10.8 (for https://github.com/geekan/MetaGPT/issues/282)
copier<8.1.0

**Comment by yajo** [comment]
Do you have an example? What commands should I run to reproduce the problem?

**Comment by yajo** [comment]
Fixed by #210
