### ISSUE TITLE
pre-commit: some hooks not fails(pylint-odoo). ruff has something to do with it?

### ISSUE THREAD

**Issue by celm1990** [OCA/oca-addons-repo-template#230]
## Describe the bug
I made a module for example with some inconsistencies, but pre-commit with ruff not fails

## To Reproduce
**Affected versions**:
new linter with `ruff`

1. Generate a new Repo using `oca-addons-repo-template` 
**Command executed**
`copier copy --UNSAFE https://github.com/OCA/oca-addons-repo-template.git repo_with_ruff`
2. Answer questions and [enable `ruff`](https://github.com/celm1990/repo_with_ruff/blob/17.0/.copier-answers.yml#L25)
3. Add a module with some code and run` pre-commit run -a`

**Expected behavior**
pylint-odoo must be fails because:
- Manifest version is wrong(16.0 instead of 17.0)
- Line to long
- Text untranslate

**Additional context**
Please see repo where pre-commit not fail
https://github.com/celm1990/repo_with_ruff/actions/runs/6841841712/job/18602672369

@sbidoul can you give feedback if any additional config is need? I only answer but not add `additional_ruff_rules`

**Comment by celm1990** [comment]
UPDATE:
I have updated the pre-commit configuration to utilize `flake8` instead of `ruff`. Now, the check for maximum length is functioning as expected. You can view the results at the following link: 
https://github.com/celm1990/repo_with_ruff/actions/runs/6842006335/job/18603029663
So, It seems that 'ruff' is missing some configuration @sbidoul?.

However, there is an issue with pylint-odoo; I observed a new release  https://github.com/OCA/pylint-odoo/releases/tag/v9.0.1 but the repository is currently using  https://github.com/OCA/pylint-odoo/releases/tag/v8.0.19

**Comment by celm1990** [comment]
UPDATE 2:
pylint-odoo ` 7.0.2`(used to Odoo V16)  is working, So I suspicious some change from 7.0.2 to V8.0 is not working @moylop260 can you review please, I not found CHANGELOG on `pylint-odoo`
![image](https://github.com/OCA/oca-addons-repo-template/assets/7775116/28a12806-caa9-444b-8dea-c16b143d8ed8)

**Comment by sbidoul** [comment]
I'm enabling E501 in #231 

Regarding pylint-odoo, I don't see how it's behaviour could be influenced by the ruff config. What make you think it does?

As far as I can tell, the configuration is identical as for 16.0 (no one proposed enhancements for 17), so if a problem is present, it was likely present in 16 too.

**Comment by celm1990** [comment]
> I'm enabling E501 in #231

Thanks so much

> 
> Regarding pylint-odoo, I don't see how it's behaviour could be influenced by the ruff config. What make you think it does?
> 
I'm suspicious, but based on my latest comment, the change from v8.0.5 to v8.0.6 could alter behavior, possibly due to [this commit](https://github.com/OCA/pylint-odoo/commit/e0df7c62031d201a1df1a314b65d54b9e67d4a30). Sorry  for mixin with ruff

**Comment by celm1990** [comment]
I close this issue
- error related to isort and ruff is working now, thanks @sbidoul 
- I create a new issue for pylint-odoo https://github.com/OCA/pylint-odoo/issues/476
