### ISSUE TITLE
[Question] hook for oca-gen-addon-readme is not generated in .pre-commit-config.yaml for odoo 13.0 and below

### ISSUE THREAD

**Issue by AungKoKoLin1997** [OCA/oca-addons-repo-template#237]
I tried to update my repo that is odoo 13.0 and I don't see oca-gen-addon-readme hook in .pre-commit-config.yaml.
But it is generated for other repos that are above v13.0. I tried to follow up the commit history of oca-addons-repo-template and I still don't see any commit about this.

Is it intentional workflow or bug?

@qrtl

**Comment by pedrobaeza** [comment]
Yes, 13.0 is not included due to python versions involved AFAIK.
