### ISSUE TITLE
Pre-commit is formatting SVG files

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-addons-repo-template#25]
You can see it in https://github.com/Tecnativa/partner-contact/commit/97ef1fb6681f2a265acf49546615ff9fc5d83333?short_path=5d4c7b3#diff-5d4c7b37672483c29d7198f8bb94170ce8b35c0e10793dbc9f41016eaa1ab41b

Which I think it shouldn't happen, as that file is not intended to be read at code level.

**Comment by sbidoul** [comment]
@yajo wdyt ?

**Comment by Yajo** [comment]
I think it's positive that prettier handles those files. Different SVG editors might change whitespace at will, and this way we have a more significative diff and more readable source. Asking humans to review it is not good, but as long as it's automated I don't see any problems.

**Comment by sbidoul** [comment]
In general I'd rather not prettify tool-generated files. Otherwise pre-commit constantly fights against the output produced by the tool (the drawing tool in this case).

**Comment by pedrobaeza** [comment]
I agree with @sbidoul. If I use Inkscape for changing something on the SVG file, we will have constant reformattings there.

**Comment by pedrobaeza** [comment]
Another one affected by the SVG re-formatting: https://github.com/OCA/partner-contact/pull/1024

Can you please exclude that files?

**Comment by sbidoul** [comment]
:+1: to add svg files to the globale exclude section.
