### ISSUE TITLE
pre-commit/mirrors-prettier has been archived

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-addons-repo-template#264]
The https://github.com/pre-commit/mirrors-prettier repo has been archived without much explanation.

There is some discussion in https://github.com/prettier/prettier/issues/15742

We may need to look for an alternative.

**Comment by PabloEForgeFlow** [comment]
I was looking at some of the proposed solutions in the discussion, and using [local hooks](https://pre-commit.com/#repository-local-hooks) (https://github.com/prettier/prettier/issues/15742#issuecomment-2180420244) seems quite reasonable to me. We would need to pull in all the keys from [.pre-commit-hooks.yaml](https://github.com/pre-commit/mirrors-prettier/blob/main/.pre-commit-hooks.yaml), but I think it's simple enough that it shouldn't be a problem.

We could perhaps do the same for `eslint` and remove the dependency on the repo, in case something similar happens to it.

**Comment by sbidoul** [comment]
@PabloEForgeFlow that sounds worth trying, yes.

**Comment by PabloEForgeFlow** [comment]
Good to hear, I'll get something working and do a PR.

We will probably want to update the version for both of them in v18 right? They've both had new major versions with breaking changes (`prettier` in [v3.0.0](https://prettier.io/blog/2023/07/05/3.0.0.html) and `eslint` in [v9.0.0](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/)), so I'm not sure if we should only update to the latest minor version.

**Comment by sbidoul** [comment]
Yes let's use the latest versions in 18. If we don't wait too much, we can still push it to the 18.0 branches. The more we wait, the more we risk making branches red and create trouble for maintainers, though.

**Comment by PabloEForgeFlow** [comment]
@sbidoul Hey Stéphane, could you take a look at https://github.com/OCA/oca-addons-repo-template/pull/278?

**Comment by sbidoul** [comment]
Yes yes, it's on my radar :sweat:

**Comment by PabloEForgeFlow** [comment]
> Yes yes, it's on my radar 😓

Sorry, I didn't mean to pressure you. I thought the notification might have gotten lost among the many things that are going on. :bow:

**Comment by sbidoul** [comment]
No worries :) I made a couple of quick comments, and I'll try to test this week still.
