### ISSUE TITLE
Generate oca_dependencies.txt

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-addons-repo-template#32]
I've a WIP script, but I'd rather deploy v1.0.3 without it so assigning this one to the next milestone.

**Comment by legalsylvain** [comment]
Nice idea.
Could you explain from wich info you will base to generate the file ?

**Comment by sbidoul** [comment]
> from wich info you will base to generate the file

- The `website` key in manifests which in turn we get from the wheels published at https://wheelhouse.odoo-community.org/oca-simple/
- Any override branch or PR found in `test-requirements.txt`

This will be enabled only in `MQT_DEP=PIP` mode (as opposed to the `requirements.txt` which can be generated always - see #31).
