### ISSUE TITLE
[14.0] prettier-xml: A little bit too invasive

### ISSUE THREAD

**Issue by rousseldenis** [OCA/oca-addons-repo-template#34]
I had issue with a report : https://travis-ci.com/github/OCA/event/jobs/406980086#L369

prettier-xml is adding carriage return to xml values. In that case, this is annoying as Odoo does not trim, so when installing, the reference to the report is not found.

Values shouldn't be modified.

**Comment by pedrobaeza** [comment]
Another similar case:

https://github.com/OCA/community-data-files/pull/99#discussion_r510832164

It seems this needs to put the prettier xml as strict.

cc @Yajo @sbidoul

**Comment by Yajo** [comment]
Fix in #35.
