### ISSUE TITLE
Missing pylint checks

### ISSUE THREAD

**Issue by simahawk** [OCA/oca-addons-repo-template#37]
I'm testing this on an existing v13 repo (https://github.com/OCA/connector-interfaces).
I've generated it from scratch and compared to the original setting it seems we miss these checks for pylint:

* `missing-import-error` in .pylintrc and .pylintrc-mandatory
* `missing-manifest-dependency` in .pylintrc-mandatory

Is this by decision or by error?

**Comment by sbidoul** [comment]
@simahawk this was by decision. See https://github.com/OCA/oca-addons-repo-template/pull/20 for the explanation.

**Comment by simahawk** [comment]
@sbidoul I see, thanks for the pointer :)
