### ISSUE TITLE
[RFC] disable pre-commit for some subdirectory

### ISSUE THREAD

**Issue by legalsylvain** [OCA/oca-addons-repo-template#40]
Hi all, 

i'm using in my custom repos, all the OCA pre-commit stuff and all the checks, to stick with the OCA conventions.

in one of my repository, i have some monkey patch regarding odoo code, so I want to disable the checks for that part because I don't want to reformat the Odoo code, to make me more simple the analysis of diff.

(OCA exemple : https://github.com/OCA/pos/blob/8.0/pos_pricelist/models/pos_order_patch.py)

What is the correct syntax to disable all the checks for subfolders only ? do you have any exemple ?

thanks in advance.

**Comment by astirpe** [comment]
[Here](https://github.com/OCA/l10n-netherlands/blob/13.0/.prettierignore) is an example of how to skip the automatic reformatting of a particular file: by adding its path in the .prettierignore

**Comment by legalsylvain** [comment]
thanks @astirpe ! I'll give it a try.

**Comment by Yajo** [comment]
That's just for prettier, but you might be speaking about black.

On a global level, pre-commit supports exclude: https://pre-commit.com/#top_level-exclude

On a more specific level, you can use that exclude per task, or you can check each tool options (black, autoflake, prettier...).

This is more a discussion than an issue, so I'm closing here.
