### ISSUE TITLE
Distribute github cron actions over time?

### ISSUE THREAD

**Issue by hbrunn** [OCA/oca-addons-repo-template#67]
after activating the stale action for web, I [noticed](https://github.com/OCA/web/pull/2037) this doesn't touch all open PRs/issues because of limits. With the proposal we're already in a better situation, but probably still won't be able to cover them all.

Given the limits are per hour, should we distribute this cronjob over different hours for different repos and increase the number of operations as the [docs propose](https://github.com/actions/stale#operations-per-run)?

I could imagine: Keep everything as it is, but for server-tools, web and whatever else is huge run at a different hour than the rest, and bump operations to ie 500.

Does anyone have a complete overview how OCA uses the REST API?

**Comment by pedrobaeza** [comment]
Link with https://github.com/OCA/web/pull/2037

**Comment by sbidoul** [comment]
Not sure would help but organization-wide workflow seem to be planned for Q2 2022: https://github.com/github/roadmap/issues/52

**Comment by sbidoul** [comment]
> Does anyone have a complete overview how OCA uses the REST API?

@hbrunn I'm not aware of such a list. Of the top of my head we have

- the oca-gitbub-bot
- the team sync scripts
- the CLA bot
- possibly the github connector in the OCA Odoo instance

Capping the operations the stale bot can do sounds like a good idea if this helps avoid starving other more critical processes.

**Comment by Yajo** [comment]
The stale action runs Sundays at 12:00, so I guess the limit is `30 * $oca_repo_count` because all those calls will be done with not much timediff. If they all use the same token, then the limit is nice because we have lots of repos. #68 should make the action more performant now.
