### ISSUE TITLE
Creation of the 14.0 branches

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-addons-repo-template#7]
I'm creating this issue to track the creation of 14.0 branches.

Questions to be resolved beforehand

- [x] how to manage the repo-level README (#6) ?
- [x] do we need any updates to linter configurations compared to 13.0 ?
  - [x] use latest version of linters in .pre-commit-config.yaml (black, prettier, etc)

TODO

- [x] update this template to support 14.0 (#8)
- [x] prepare branch initialization the script (https://github.com/OCA/maintainer-tools/pull/472)
- [ ] prepare the branch update script (in oca-github-bot)

**Comment by pedrobaeza** [comment]
I think we have to take the occasion to update black and prettier versions and use the same strategy as in 13.0 (a previous commit executing them for any possible change - they should be the less and for the good though).

I created https://github.com/OCA/maintainer-tools/blob/master/tools/migrate_branch_empty.py for adding past versions, that doesn't require any local copy (all through GitHub API), but not sure if you can use it now in combination with Prettier.

**Comment by sbidoul** [comment]
@Yajo sure, go ahead, it's most welcome :)

**Comment by lmignon** [comment]
I discover the proposed repo template. IMO it's a good idea to me to have a way to easily maintain consistency in all OCA repositories.  Nevertheless, I wonder why there is a git submodule to maintainer-tools? I'm not fan of git submodules and I wonder about the motivations behind this choice.

**Comment by lmignon** [comment]
> Nevertheless, I wonder why there is a git submodule to maintainer-tools? I'm not fan of git submodules and I wonder about the motivations behind this choice.

Response from sbidoul into the mailing list....
The test and vendor directories you mention are related to the templating mechanism. They are not part of the actual target repos.

**Comment by Yajo** [comment]
See #8.

**Comment by sbidoul** [comment]
Ok, one PR to go: #3 and I'll push the 14.0 branch everywhere.

Examples results: https://github.com/OCA/server-tools/tree/14.0 and https://github.com/OCA/mis-builder/tree/14.0.

**Comment by sbidoul** [comment]
I tagged v1.0.2. The update script will be for another time.
