### ISSUE TITLE
repos_with_ids maintenance

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-addons-repo-template#87]
This template needs maintainer tools' `repos_with_ids.txt` to generate the runbot link.
To this ends it vendors it as a submodule.
The problem with this approach is that this submodule reference must be updated whenever we add a repo in `repos_with_ids.txt`.

Is there another approach possible with copier ?

**Comment by sbidoul** [comment]
Actually, we should get rid of this repos_with_ids hack. We should generate a runbot link that includes the repo name, and let any necessary redirection on runbot side.

**Comment by pedrobaeza** [comment]
Last time we checked that, runbot was able to do that.

**Comment by sbidoul** [comment]
At the minimum, we can do the redirection in runbot's nginx.

In the meantime I've updated the vendored maintainer tools in 95c8a24d1d6a21ea5d8208433e18e519a5fb4f92

**Comment by pedrobaeza** [comment]
But are we going to maintain runbot at the end? I understood that you were working in another thing (runboat?).

**Comment by sbidoul** [comment]
Yes, I'm experimenting with something simple based on kubernetes. It's not ready yet but looks promising.
The problem with runbot is that it's becoming a monster that does everything conceivable automation for Odoo SA which do not necessarily align with our needs.

In any case if we change runbot, the URLs and repo ids will probably change, so some kind of redirection on runbot side will be necessary.

So its time to progressively retire repos_with_ids, I think. AFAICT, they are used

- here (for README.md)
- in oca-gen-addon-readme
- in github-connector

**Comment by pedrobaeza** [comment]
Well, changing this template and applying to the suitable repos + changing the README generator and applying it the same will replace all runbot links (and we should also change the nomenclature on for example the badge), so I think the redirection may not be necessary. All depends on the needed effort to make it work. If it's not too much, then why not. But if it takes a lot, better to focus on perform the other change IMO.

I think the runbot ID is not used in the github connector for anything.

**Comment by Yajo** [comment]
> Actually, we should get rid of this repos_with_ids hack. We should generate a runbot link that includes the repo name, and let any necessary redirection on runbot side.

This seems a good solution indeed.

Regarding the runbot change, although a bit off-topic... Have you considered Gitpod? OK, I know that it's more suited for quick disposable development environments, but actually it allows to bootstrap a sicekick service automatically and notifying the user. Just let me showcase how it works in copier itself and I think you'll get the point:

https://user-images.githubusercontent.com/973709/140029892-34043307-b656-458e-9906-6aa639ea900f.mp4

It's also free for FLOSS projects, and it's FLOSS itself, runnable on Kubernetes. And you can use the browser extension, which allows you to open a PR on gitpod in a single click, and it checks out a branch to push directly to the PR if you have permissions.

It's really quite amazing.

**Comment by sbidoul** [comment]
This was done in https://github.com/OCA/oca-addons-repo-template/pull/91
