### ISSUE TITLE
travis_apt_packages not generated for github actions

### ISSUE THREAD

**Issue by etobella** [OCA/oca-addons-repo-template#96]
When adding a travis_apt_package I expected that the packages will be used also on Github actions but they weren't added.

It can be seen here:
https://github.com/OCA/edi/pull/488

https://github.com/OCA/edi/commit/87a686563a5aa17b799b3c53aca0c88e6e5bdc89
https://github.com/OCA/edi/compare/87a686563a5aa17b799b3c53aca0c88e6e5bdc89..8aeed2429022f3820b88366db3162806b6868daf

**Comment by pedrobaeza** [comment]
Although the question text leads to Travis, it should be reused for GH actions as well. Maybe it's the moment now to add a new neutral question `apt_packages` that feeds both parts, and keep the old `travis_apt_packages` for compatibility.

**Comment by sbidoul** [comment]
You can now declare apt packages in manifest external dependencies using a "deb" key. This way the oca-ci will install them, as well as runboat, without having to parse the ci config, as travis2docker does.

**Comment by pedrobaeza** [comment]
OK, that's great. Maybe an entry in some wiki to point to this FAQ?
