### ISSUE TITLE
[Security] Workflow pre-commit.yml is using vulnerable action pre-commit/action

### ISSUE THREAD

**Issue by igibek** [OCA/oca-addons-repo-template#99]
The workflow pre-commit.yml is referencing action pre-commit/action using references v2.0.0. However this reference is missing the commit [80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7](https://github.com/pre-commit/action/commits/80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by sbidoul** [comment]
Issue transferred here from oca/mis-builder where it was originally opened

**Comment by sbidoul** [comment]
It is also to be noted that the pre-commit action is now in maintenance mode and will not evolve.
We may want to take over with explicit steps and caching in this template.

**Comment by pedrobaeza** [comment]
No replacement available at GH?

**Comment by joao-p-marques** [comment]
Can't we just bump the version [here](https://github.com/OCA/oca-addons-repo-template/blob/master/src/.github/workflows/pre-commit.yml.jinja#L20)?

**Comment by joao-p-marques** [comment]
Looks like that commit is included in `v2.0.1` and onward

**Comment by sbidoul** [comment]
> Can't we just bump the version [here](https://github.com/OCA/oca-addons-repo-template/blob/master/src/.github/workflows/pre-commit.yml.jinja#L20)?

I think so, yes. v2.0.3 should be fine.
